name = "example-d1"
main = "_build/js/release/build/app/app.js"
compatibility_date = "2024-12-01"

[[d1_databases]]
binding = "DB"
database_name = "blog-db"
database_id = "local-dev-db"
migrations_dir = "db/migrations"
